name: CASA
symbol: CASA
decimals: 9
address: EQBWK_VVEBJWiIQIIXOckUVw0HdF24buJiNiiR0dUHEe2xs4
description: CASA Token – utility token of the Casafond ecosystem on TON.
image: logo.png
social:
  website: https://casafond.org
  telegram: https://t.me/+9aE3Jx-WTz0wM2Uy
